apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: internet-banking
  labels:
    app: user-service
    tier: business
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: user-service
